apiVersion: v1
kind: Pod
metadata:
  name: trivy-db-shell
  namespace: default
spec:
  nodeSelector:
    nodegroup-type: ddocdoc-spot
  restartPolicy: Never
  containers:
    - name: shell
      image: alpine:3.20
      command: ["sh", "-c", "sleep 36000"]
      volumeMounts:
        - name: trivy-db
          mountPath: /cache/trivy/db
  volumes:
    - name: trivy-db
      persistentVolumeClaim:
        claimName: trivy-db