apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-db
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc-trivy